# permissions for end users to edit mycharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mychart-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-operator
    app.kubernetes.io/part-of: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: mychart-editor-role
rules:
- apiGroups:
  - charts.example.com
  resources:
  - mycharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.example.com
  resources:
  - mycharts/status
  verbs:
  - get
