# permissions for end users to view mycharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mychart-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-operator
    app.kubernetes.io/part-of: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: mychart-viewer-role
rules:
- apiGroups:
  - charts.example.com
  resources:
  - mycharts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.example.com
  resources:
  - mycharts/status
  verbs:
  - get
